{
  "hash": "b3a49b675c84905d479d5161451e506e",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Assignment 2: Spatial Analysis and Visualization\"\nsubtitle: \"Healthcare Access and Equity in Pennsylvania\"\nauthor: \"Angel Rutherford\"\ndate: today\nformat: \n  html:\n    code-fold: false\n    toc: true\n    toc-location: left\n    theme: cosmo\n    embed-resources: true\nexecute:\n  warning: false\n  message: false\n---\n\n\n\n\n## Part 1: Healthcare Access for Vulnerable Populations\n\n### Research Question:\n\n**Which Pennsylvania counties have the highest proportion of vulnerable populations (elderly + low-income) living far from hospitals?**\n\n#### Step 1: Data Collection \n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Load required packages\nlibrary(sf)\nlibrary(tidyverse)\nlibrary(tigris)\nlibrary(tidycensus)\nlibrary(scales)\nlibrary(patchwork)\nlibrary(knitr)\n\n# Set Census API key\ncensus_api_key(\"42bf8a20a3df1def380f330cf7edad0dd5842ce6\")\n\n# Load spatial data\npa_counties <- st_read(\"./data/Pennsylvania_County_Boundaries.shp\")\nhospitals <- st_read(\"./data/hospitals.geojson\")\ncensus_tracts <- tracts(state = \"PA\", cb = TRUE)\n\n# Check that all data loaded correctly\npa_counties\nhospitals\ncensus_tracts\n```\n:::\n\n\n\n\nThere are **223 hospitals** and **3445 census tracts** in the datasets. The coordinate reference system for each dataset is as follows: **WGS 84 / Pseudo-Mercator** for county data, **WGS 84** for the hospital data, and **NAD83** for the census tracts.\n\n---\n\n#### Step 2: Get Demographic Data \n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Get demographic data from ACS\n\ntract_data <- get_acs(\n  geography=\"tract\",\n  variables= c(\n    total_pop = \"B01003_001\",\n    median_income = \"B19013_001\"\n  ),\n  state = \"PA\",\n  year = 2022,\n  output = \"wide\"\n)\n\nover_65 = c(\"B01001_020\",\"B01001_021\",\"B01001_022\",\"B01001_023\",\n            \"B01001_024\",\"B01001_025\",\"B01001_044\",\"B01001_045\",\n            \"B01001_046\",\"B01001_047\",\"B01001_048\",\"B01001_049\")\n\nelderly_data = get_acs(\n  geography=\"tract\",\n  variables =c(over_65\n),\n  state = \"PA\",\n  year = 2022,\n  output = \"wide\"\n)\n\nover_65_E<- paste0(over_65, \"E\")\n\nelderly_data<- elderly_data%>%\n  mutate(elderly_pop = rowSums(elderly_data[, over_65_E], na.rm = TRUE))\n  \ntotal_elderly <-elderly_data%>%\n  select(GEOID,elderly_pop)\n\ntract_data <-left_join(tract_data, total_elderly, by=\"GEOID\")\n\n# Join to tract boundaries\n\ndata_with_bounds = left_join(census_tracts, tract_data, by=\"GEOID\")\ndata_with_bounds\n\nno_record= sum(is.na(tract_data$median_incomeE))\nno_record\n\nmedian_median= median(tract_data$median_incomeE, na.rm = TRUE)\nmedian_median\n```\n:::\n\n\n\nThe ACS data being used in this analysis is from **2022**. Excluding the **63 tracts** with missing income data, the median income across PA census tracts was **$70,188**.\n\n---\n\n\n#### Step 3: Define Vulnerable Populations \n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Filter for vulnerable tracts based on your criteria\ndata_with_bounds <- data_with_bounds%>%\n  mutate(\n    elderly_pct = elderly_pop/total_popE * 100)\n\nvulnerable_data <- data_with_bounds%>%\n  filter(median_incomeE < 36000 & elderly_pct > 20) \n  \n\nvulnerable_data\n\nprint((nrow(vulnerable_data)/nrow(data_with_bounds))*100)\n```\n:::\n\n\n\nThe income threshold I chose to identify tracts with low median income was a income less than **$36,000**, **approximately half of the median of all tracts**. The threshold used to identify large elderly populations was a population over **20%** elderly as it would indicate that **more than 1/5th of the tract's population was elderly**. These thresholds were defined to serve as measurements of tract vulnerability. Based on these vulnerability thresholds, **49 tracts** or **1.4%** of Pennsylvania census tracts were considered vulnerable.\n\n---\n\n\n#### Step 4: Calculate Distance to Hospitals \n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Transform to appropriate projected CRS\nvulnerable_data <- st_transform(vulnerable_data,3365)\nhospitals <- st_transform(hospitals, 3365)\n\n# Calculate distance from each tract centroid to nearest hospital\nvulnerable_distance <- vulnerable_data%>%\n  mutate(\n    distance_to_nearest= as.numeric(apply(st_distance(st_centroid(.),hospitals),\n    1, min)\n  ))\n\nvulnerable_distance\n\nmedian_distance= median(vulnerable_distance$distance_to_nearest , na.rm = TRUE)\nmedian_distance\n\nmax_distance = max(vulnerable_distance$distance_to_nearest , na.rm = TRUE)\nmax_distance\n```\n:::\n\n\nThe datasets' projected coordinate reference system were transformed to **3365**, **the ideal projection for Pennsylvania** and for **measuring distance in units** and **not distorting degrees of longitude and latitude**. The average distance to the nearest hospital for vulnerable tracts was approximately **6395 feet**. The maximum distance was about **98,596 feet**. **Only 1 tract**, out all the vulnerable tracts, was more than 15 miles from the nearest hospital.\n\n---\n\n\n\n#### Step 5: Identify Underserved Areas \n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create underserved variable\nunderserved_tracts <- vulnerable_distance%>%\n  filter(distance_to_nearest > 79200)\n\nunderserved_tracts\n\nprint((nrow(underserved_tracts)/nrow(vulnerable_data))*100)\n```\n:::\n\n\n**Only one singular tract** is considered underserved by the condition of being more than 15 miles or 79,200 feet from the nearest hospital. This means that **2%** of tracts identified as vulnerable are underserved. Considering that Pennsylvania is overwhelmingly rural, I **am** surprised that many vulnerable tracts have a hospital within 15 miles.  \n\n---\n\n\n#### Step 6: Aggregate to County Level\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Spatial join tracts to counties\nvulnerable_distance <- st_transform(vulnerable_distance, st_crs(pa_counties))\n\ntracts_per_county <- vulnerable_distance %>% \n  st_join(pa_counties) %>%\n  st_drop_geometry() %>%\n  group_by(COUNTY_NAM)\n\n\n# Aggregate statistics by county\ncounty_vulnerability <- tracts_per_county %>%\n  summarise(\n    num_of_tracts = n(),\n    num_of_underserved = sum(distance_to_nearest > 79200, na.rm = TRUE),\n    pct_underserved =  num_of_underserved/num_of_tracts *100,\n    avg_distance = mean(distance_to_nearest, na.rm = TRUE),\n    total_vulnerable = sum(total_popE, na.rm = TRUE)\n  )%>%\n  arrange(desc(avg_distance))\n\nformated_county_vulnerability <- county_vulnerability%>%\n  mutate(\n    total_vulnerable = comma(total_vulnerable),\n    avg_distance = comma(avg_distance),\n    pct_underserved = percent(pct_underserved/100)\n  )\n\nformated_county_vulnerability%>%  \n  select(COUNTY_NAM, num_of_underserved, num_of_tracts, pct_underserved, avg_distance, total_vulnerable)%>%\n    kable(\n      col.names = c(\n\"County Name\", \"Number of Underserved Tracts\",\n\"Total Number of Vulnerable Tracts\", \"Percentage Underserved\", \"Average Distance\", \"Total Vulnerable Population\"),\n     digits=c(0,1,1,1,1))\n```\n\n::: {.cell-output-display}\n\n\n|County Name    | Number of Underserved Tracts| Total Number of Vulnerable Tracts|Percentage Underserved |Average Distance |Total Vulnerable Population |\n|:--------------|----------------------------:|---------------------------------:|:----------------------|:----------------|:---------------------------|\n|CAMERON        |                            1|                                 1|100%                   |98,596           |1,988                       |\n|NORTHUMBERLAND |                            0|                                 1|0%                     |50,187           |2,350                       |\n|BEAVER         |                            0|                                 1|0%                     |21,733           |2,093                       |\n|LEHIGH         |                            0|                                 1|0%                     |17,985           |3,974                       |\n|WESTMORELAND   |                            0|                                 3|0%                     |16,963           |3,927                       |\n|LUZERNE        |                            0|                                 3|0%                     |13,026           |7,931                       |\n|ALLEGHENY      |                            0|                                15|0%                     |11,849           |27,204                      |\n|DELAWARE       |                            0|                                 1|0%                     |11,338           |2,373                       |\n|MIFFLIN        |                            0|                                 1|0%                     |9,779            |2,418                       |\n|YORK           |                            0|                                 1|0%                     |8,109            |1,659                       |\n|MERCER         |                            0|                                 2|0%                     |5,722            |4,992                       |\n|CRAWFORD       |                            0|                                 1|0%                     |4,899            |2,842                       |\n|WAYNE          |                            0|                                 1|0%                     |4,419            |4,469                       |\n|FAYETTE        |                            0|                                 1|0%                     |3,726            |3,205                       |\n|PHILADELPHIA   |                            0|                                11|0%                     |3,538            |35,060                      |\n|CAMBRIA        |                            0|                                 2|0%                     |3,223            |3,241                       |\n|LAWRENCE       |                            0|                                 1|0%                     |2,743            |3,893                       |\n|LACKAWANNA     |                            0|                                 1|0%                     |2,651            |2,901                       |\n|BLAIR          |                            0|                                 1|0%                     |2,192            |1,436                       |\n|ERIE           |                            0|                                 2|0%                     |1,238            |3,070                       |\n\n\n:::\n:::\n\n\n\n\n**Only 1 county**, Cameron county, has **100%** underserved vulnerable tracts. **Allegheny county** has the most vulnerable people, 27,204, living far away, about 11,849 feet, from hospitals. There are no patterns in underserved counties but there is a pattern in vulnerability as **most vulnerable counties have vulnerable populations less than 5,000**, indicating counties with smaller overall population.\n\n---\n\n#### Step 7: Create Summary Table \n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create and format priority counties table\ntop_10_counties <- formated_county_vulnerability %>%\n  slice_head(n=10)\n\n# Format as table with kable() - include appropriate column names and caption \ntop_10_counties %>%\n  select(COUNTY_NAM, pct_underserved, avg_distance, total_vulnerable)%>%\n    kable(\n      col.names = c(\n\"County Name\", \n\"Percentage of Tracts Lacking Adequate Access to Hospitals (over 15 miles to nearest)\",\n\"Average Distance to Nearest Hospital (ft)\",\n\"Total Population of Vulnerable Tracts (tracts with 20% over the age of 65 and a median income less than 3600)\"),\n      caption = \"Top 10 Pennslyvania Counties to Prioritize Healthcare Investments Based on Vulnerability and Access\",\n     digits=c(0,1,1,1)\n)\n```\n\n::: {.cell-output-display}\n\n\nTable: Top 10 Pennslyvania Counties to Prioritize Healthcare Investments Based on Vulnerability and Access\n\n|County Name    |Percentage of Tracts Lacking Adequate Access to Hospitals (over 15 miles to nearest) |Average Distance to Nearest Hospital (ft) |Total Population of Vulnerable Tracts (tracts with 20% over the age of 65 and a median income less than 3600) |\n|:--------------|:------------------------------------------------------------------------------------|:-----------------------------------------|:-------------------------------------------------------------------------------------------------------------|\n|CAMERON        |100%                                                                                 |98,596                                    |1,988                                                                                                         |\n|NORTHUMBERLAND |0%                                                                                   |50,187                                    |2,350                                                                                                         |\n|BEAVER         |0%                                                                                   |21,733                                    |2,093                                                                                                         |\n|LEHIGH         |0%                                                                                   |17,985                                    |3,974                                                                                                         |\n|WESTMORELAND   |0%                                                                                   |16,963                                    |3,927                                                                                                         |\n|LUZERNE        |0%                                                                                   |13,026                                    |7,931                                                                                                         |\n|ALLEGHENY      |0%                                                                                   |11,849                                    |27,204                                                                                                        |\n|DELAWARE       |0%                                                                                   |11,338                                    |2,373                                                                                                         |\n|MIFFLIN        |0%                                                                                   |9,779                                     |2,418                                                                                                         |\n|YORK           |0%                                                                                   |8,109                                     |1,659                                                                                                         |\n\n\n:::\n:::\n\n\n\nDue to limited data availability for underserved counties, rankings were based on the ten counties with **the highest average distance**.\n\n---\n\n\n## Part 2: Comprehensive Visualization \n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create county-level access map\nhospitals <- st_transform(hospitals, st_crs(pa_counties))\ncounties_with_demographics <- pa_counties %>%\n  left_join(county_vulnerability, by = \"COUNTY_NAM\")\n\nggplot(counties_with_demographics) +\n  geom_sf(aes(fill = pct_underserved), color = \"black\", size = 0.5) +\n  geom_sf(data = hospitals, color = \"red\", size = 2) +\n  scale_fill_viridis_c(\n    na.value = \"white\",\n    name = \"Percentage Underserved\",\n    labels = scales::label_number(suffix = \"%\"),\n    option = \"plasma\"\n  ) +\n  labs(\n    title = \"Pennsylvania Counties with Vulnerable Tracts\\nand their Percentage of Underserved Vulnerable Tracts\",\n    subtitle = \"Red = Hospitals\",\n    caption = \"Source: ACS 2022\"\n  ) +\n  theme_void()+\n  theme(\n  plot.title = element_text(face = \"bold\", hjust =0))\n```\n\n::: {.cell-output-display}\n![](Rutherford_Angel_Assignment2_files/figure-html/unnamed-chunk-8-1.png){width=672}\n:::\n:::\n\n\n\n---\n\n\n### Map 2: Detailed Vulnerability Map \n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhospitals <- st_transform(hospitals, st_crs(pa_counties))\nhospitals_with_counties <- hospitals %>%\n  st_join(pa_counties %>% select(COUNTY_NAM))\n\ncensus_tracts <- st_transform(census_tracts, st_crs(pa_counties))\n\ntarget_county <- pa_counties %>%\n  filter(FIPS_COUNT == underserved_tracts$COUNTYFP)\n\nmy_neighbors <- pa_counties %>%\n  st_filter(target_county, .predicate = st_touches)\n\n\nclipped_neighbor_tracts <- st_intersection(census_tracts, my_neighbors)\nclipped_target_tracts <- st_intersection(census_tracts, target_county)\n\nneighbor_hospitals <- hospitals_with_counties %>%\n  filter(COUNTY_NAM %in% my_neighbors$COUNTY_NAM)\n\nggplot()+\n  geom_sf(data = clipped_neighbor_tracts, color=\"black\")+\n  geom_sf(data = clipped_target_tracts, color=\"black\")+\n  geom_sf(data = target_county, fill=\"lightgray\", color=\"black\", alpha=0.7)+\n  geom_sf(data = my_neighbors, fill=\"white\", color=\"black\", alpha=0.7)+\n  geom_sf(data = underserved_tracts, fill= \"blue\")+\n  geom_sf(data = neighbor_hospitals, color=\"red\", size=2)+\n  labs(\n    title = \"Surrounding Pennsylvania Counties and Tracts of the Underserved Tract\",\n    subtitle = \"Red = Hospitals, Blue = Underserved Tract\",\n    caption = \"Source: ACS 2022\")+\n  theme_void()+\n  theme(\n    plot.title = element_text(face = \"bold\", hjust = 0.5))\n```\n\n::: {.cell-output-display}\n![](Rutherford_Angel_Assignment2_files/figure-html/unnamed-chunk-9-1.png){width=672}\n:::\n:::\n\n\n\n---\n\n### Chart: Distribution Analysis\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create distribution visualization\n\nggplot(county_vulnerability, aes(x = COUNTY_NAM, y = avg_distance)) +\n  geom_col(fill = \"blue\", color = \"black\") +\n  labs(title = \"Bar Plot Average Distance to Hospitals Across Vulnerable Tracts By County\",\n       x = \"County Name\", \n       y = \"Average Distance (feet)\") +\n  theme_minimal()+\n  theme(axis.text.x = element_text(angle = 45, hjust = 1),\n  panel.grid.major = element_blank())\n```\n\n::: {.cell-output-display}\n![](Rutherford_Angel_Assignment2_files/figure-html/unnamed-chunk-10-1.png){width=672}\n:::\n:::\n\n\nThis bar chart shows the average distance to hospitals across vulnerable tracts by Pennsylvania counties. Cameron County stands out dramatically with the highest value, suggesting that residents there may face significant challenges accessing hospital care. Most other counties have relatively low averages, indicating better proximity to healthcare facilities.\n\n---\n\n\nPer previous submission feedback, I removed instructional text from the final version of my assignment. Additionally, I omitted tables and outputs that were generated for my personal reference.\n\n---\n",
    "supporting": [
      "Rutherford_Angel_Assignment2_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}